/**
 * SilicOne - Product Data (18 supplier images + 2 AI images)
 * 20 B2B SKUs with real supplier product photos
 */
var products = [
  // --- Category: Nose Pads (4) ---
  { id:"NP-001",category:"nose",name:"Adhesive Silicone Heightening Nose Pads",nameCN:"自粘式硅胶增高鼻托",image:"images/products/NP-001.jpg",specs:{material:"Food-grade silicone (FDA)",size:"11×7mm, 3 heights (1.5/2.5/3.5mm)",color:"Transparent, Black, Beige",packaging:"OPP bag + card, 10/20/50 pairs per pack"},pricing:[{qty:"100-500",price:"$0.12/pair"},{qty:"500-2000",price:"$0.08/pair"},{qty:"2000-10000",price:"$0.05/pair"},{qty:"10000+",price:"$0.03/pair"}],moq:100,leadtime:"3-7 days (stock) / 10-15 days (custom)",certifications:"FDA, REACH, LFGB",customOptions:"Color, hardness, logo printing, retail packaging",targetBuyers:"Optical chains, Amazon sellers, eyewear brands",description:"Premium adhesive silicone nose pads for Asian fit. Self-adhesive, 3 thicknesses.",tags:["bestseller","high-margin"]},
  { id:"NP-002",category:"nose",name:"Screw-Type Silicone Nose Pads (Oval)",nameCN:"螺丝固定式硅胶鼻托（椭圆型）",image:"images/products/NP-002.jpg",specs:{material:"Silicone with stainless steel core",size:"13×7mm oval, 10×6mm teardrop",color:"Clear, Black, Brown"},pricing:[{qty:"100-500",price:"$0.15/pair"},{qty:"500-2000",price:"$0.10/pair"},{qty:"2000+",price:"$0.07/pair"}],moq:100,leadtime:"3-7 days",certifications:"FDA, RoHS",customOptions:"Size, shape, hardness, screw type",targetBuyers:"Optical repair shops, frame manufacturers",description:"Professional screw-mounted nose pads with metal core. Compatible with metal and acetate frames.",tags:[]},
  { id:"NP-003",category:"nose",name:"Air Chamber Silicone Nose Pads (Push-In)",nameCN:"空气室硅胶鼻托（卡式）",image:"images/products/NP-003.jpg",specs:{material:"Medical-grade silicone (ISO 10993)",size:"13×7mm with air cushion",color:"Clear, Smoke Gray"},pricing:[{qty:"100-500",price:"$0.18/pair"},{qty:"500-2000",price:"$0.12/pair"},{qty:"2000+",price:"$0.08/pair"}],moq:100,leadtime:"5-10 days",certifications:"FDA, ISO 10993, REACH",customOptions:"Cushion firmness, color, size",targetBuyers:"Medical optical, premium eyewear brands",description:"Air chamber design for superior shock absorption. Medical-grade for sensitive skin.",tags:["premium"]},
  { id:"NP-004",category:"nose",name:"U-Shape Integrated Silicone Nose Pad for Kids",nameCN:"U型一体式儿童眼镜硅胶鼻托",image:"images/products/NP-004.jpg",specs:{material:"Food-grade silicone, BPA-free",size:"Universal fit kids frames (40-48mm)",color:"Transparent, Pink, Blue, Green"},pricing:[{qty:"100-500",price:"$0.60/pc"},{qty:"500-2000",price:"$0.45/pc"},{qty:"2000+",price:"$0.35/pc"}],moq:100,leadtime:"7-12 days",certifications:"FDA, LFGB, BPA-free",customOptions:"Color, animal shapes, cartoon designs",targetBuyers:"Children's eyewear brands, mom & baby retail",description:"One-piece U-shape bridge pad for children's frames. Soft, safe, comfortable.",tags:["kids","high-margin"]},

  // --- Category: Ear Hooks (9) ---
  { id:"EH-001",category:"ear",name:"Anti-Slip Silicone Ear Hooks (Temple Grips)",nameCN:"硅胶眼镜防滑耳钩 (S-22)",image:"images/products/EH-001-v2.jpg",specs:{material:"Food-grade soft silicone",size:"37×9mm, fits 6-12mm temple tips",color:"11 Colors (Black, Clear, Blue, Red, Pink, etc.)",packaging:"OPP bag / custom card packaging"},pricing:[{qty:"100-500",price:"$0.10/pair"},{qty:"500-2000",price:"$0.06/pair"},{qty:"2000-10000",price:"$0.04/pair"},{qty:"10000+",price:"$0.03/pair"}],moq:100,leadtime:"3-7 days (stock) / 10-15 days (custom)",certifications:"FDA, REACH, RoHS",customOptions:"Color matching, hardness (30-60 Shore A), custom logo/card",targetBuyers:"Amazon sellers, optical chains, sports eyewear brands",description:"Ergonomic anti-slip silicone ear grips for eyeglass temple tips. Soft food-grade silicone locks glasses comfortably in place during sports and active daily wear. Available in 11 colors.",tags:["bestseller","high-margin"]},
  { id:"EH-002",category:"ear",name:"Ergonomic Curved Silicone Ear Grips",nameCN:"人体工学弧形硅胶耳托",image:"images/products/EH-002-v2.jpg",specs:{material:"Soft silicone (40 Shore A)",size:"42×11×2.5mm, curved ergonomic",color:"Orange, Blue, Purple, Yellow, Green, Pink, etc."},pricing:[{qty:"100-500",price:"$0.15/pair"},{qty:"500-2000",price:"$0.10/pair"},{qty:"2000+",price:"$0.07/pair"}],moq:100,leadtime:"5-10 days",certifications:"FDA, LFGB",customOptions:"Multiple colors, hardness customization, custom packaging",targetBuyers:"Premium eyewear brands, sports optics",description:"Anatomically curved design for superior grip during activity. Ideal for sports and safety glasses.",tags:["premium"]},
  { id:"EH-003",category:"ear",name:"Round Silicone Anti-Slip Ear Grips (Ring Lock)",nameCN:"圆形硅胶眼镜防滑套 (S-22F)",image:"images/products/EH-003-v2.jpg",specs:{material:"High-elastic soft silicone",size:"Fit for 3-10mm temple tips (Φ14mm outer)",color:"13 Colors Available (Black, Clear, Brown, Orange, Blue, Pink, etc.)"},pricing:[{qty:"100-500",price:"$0.12/pair"},{qty:"500-2000",price:"$0.08/pair"},{qty:"2000+",price:"$0.05/pair"}],moq:100,leadtime:"3-7 days",certifications:"FDA, REACH",customOptions:"13 color choices, custom packaging cards",targetBuyers:"Optical chains, sports eyewear brands, online sellers",description:"Universal round silicone anti-slip ring locks for eyeglass temple tips. Elastic food-grade silicone securely fits 3-10mm temple arms, preventing glasses from slipping during sports and active daily wear.",tags:["bestseller","high-margin"]},
  { id:"EH-004",category:"ear",name:"Triangle Silicone Anti-Slip Ear Hooks",nameCN:"三角/逗号型硅胶眼镜防滑套 (S-22E)",image:"images/products/EH-004.jpg",specs:{material:"Food-grade soft silicone",size:"18×13mm, fits 2-10mm temple arms",color:"Black, Clear, Brown, and custom colors",packaging:"OPP bag / custom card pack"},pricing:[{qty:"100-500",price:"$0.12/pair"},{qty:"500-2000",price:"$0.08/pair"},{qty:"2000+",price:"$0.05/pair"}],moq:100,leadtime:"3-7 days (stock) / 10-15 days (custom)",certifications:"FDA, REACH, RoHS",customOptions:"Color matching, custom blister or card packaging",targetBuyers:"Optical chains, eyewear brands, Amazon/e-commerce sellers",description:"Mini triangular silicone anti-slip ear grips designed for seamless fit on thin metal and acetate temples. Ergonomic wing lock provides secure hold behind ears without uncomfortable pressure.",tags:["bestseller","high-margin"]},
  { id:"EH-005",category:"ear",name:"Kids Silicone Anti-Slip Ear Hooks (Small Size)",nameCN:"儿童小号硅胶眼镜防滑耳套 (S-22C)",image:"images/products/EH-005-v2.jpg",specs:{material:"Food-grade soft silicone (BPA-free)",size:"25×8mm, small size fits 1.5-6mm kids temples",color:"12 Colors (Red, Blue, Pink, Green, Yellow, Purple, etc.)",packaging:"OPP bag / custom hang-card packaging"},pricing:[{qty:"100-500",price:"$0.10/pair"},{qty:"500-2000",price:"$0.06/pair"},{qty:"2000+",price:"$0.04/pair"}],moq:100,leadtime:"3-7 days (stock) / 10-15 days (custom)",certifications:"FDA, LFGB, BPA-free, RoHS",customOptions:"12 colors available, custom blister or card packaging",targetBuyers:"Children's eyewear brands, optical chains, mom & baby retailers",description:"Specially designed for children's eyeglasses and small frames. Food-grade BPA-free silicone prevents glasses from slipping during sports, school, and active play. Available in 12 vibrant colors.",tags:["kids","bestseller","high-margin"]},
  { id:"EH-006",category:"ear",name:"Round Bead Silicone Anti-Slip Ear Grips",nameCN:"圆扣/飞碟型硅胶眼镜防滑耳托 (超轻0.8g)",image:"images/products/EH-006.jpg",sizeImage:"images/products/EH-006-size.jpg",specs:{material:"Food-grade ultra-soft silicone",outerDimension:"12mm × 10mm oval bead shape",slotAperture:"3mm × 1.5mm (stretches to fit)",compatibleTemples:"1mm – 10mm width (wire & acetate frames)",unitWeight:"0.8g / pair (ultra-lightweight, zero ear fatigue)",color:"10+ Colors (Black, Clear, Brown, Blue, Red, Pink, Orange, Yellow, Green, Purple)",packaging:"OPP bag / custom card pack"},pricing:[{qty:"100-500",price:"$0.10/pair"},{qty:"500-2000",price:"$0.06/pair"},{qty:"2000+",price:"$0.04/pair"}],moq:100,leadtime:"3-7 days (stock) / 10-15 days (custom)",certifications:"FDA, REACH, RoHS",customOptions:"10+ color options, custom brand card packaging",targetBuyers:"Optical retail chains, online eyewear accessory brands, Amazon sellers",description:"Ultra-lightweight (0.8g/pair) round bead silicone anti-slip ear stoppers. Oval bead design slides discreetly onto 1–10mm temple arms, locking glasses comfortably behind the ears with zero pressure.",tags:["bestseller","high-margin"]},
  { id:"EH-007",category:"ear",name:"Star Pattern Round Silicone Ear Grips (Ring Lock)",nameCN:"五角星圆形硅胶眼镜防滑套 (儿童/成人通用)",image:"images/products/EH-007-v2.jpg",specs:{material:"Food-grade soft silicone (BPA-free)",size:"Φ14mm outer diameter, fits 3-10mm temple arms",color:"11 Colors (Black, Brown, Red, Orange, Purple, Rose, Pink, Blue, Yellow, Green, Clear)",packaging:"OPP bag / custom card pack / multi-pair blister"},pricing:[{qty:"100-500",price:"$0.12/pair"},{qty:"500-2000",price:"$0.08/pair"},{qty:"2000+",price:"$0.05/pair"}],moq:100,leadtime:"3-7 days (stock) / 10-15 days (custom)",certifications:"FDA, REACH, LFGB, RoHS",customOptions:"11 color matching, custom card / blister packaging, branded pairs",targetBuyers:"Optical chains, kids & sports eyewear brands, Amazon/e-commerce sellers",description:"Star-lock round silicone anti-slip ear grips for eyeglass temple tips. Features an ergonomic star-shaped internal locking structure that slides onto 3-10mm temple arms, providing secure hold and all-day comfort without hair pulling or ear pinching. Ideal for kids, teens, and sports wear.",tags:["kids","bestseller","high-margin"]},
  { id:"EH-008",category:"ear",name:"3D Star Silicone Anti-Slip Temple Grips",nameCN:"立体五角星硅胶眼镜防滑扣 (细腿/粗腿通用)",image:"images/products/EH-008-v2.jpg",specs:{material:"Food-grade soft silicone (BPA-free)",design:"3D solid star shape with self-adaptive gripping channel",size:"13×13mm, universally fits 1.5mm–10mm temples (metal wire & acetate)",color:"Black, Brown, Navy Blue, Sky Blue, Pink, Purple, Clear",packaging:"OPP bag / custom card pack / multi-pair blister"},pricing:[{qty:"100-500",price:"$0.12/pair"},{qty:"500-2000",price:"$0.08/pair"},{qty:"2000+",price:"$0.05/pair"}],moq:100,leadtime:"3-7 days (stock) / 10-15 days (custom)",certifications:"FDA, REACH, LFGB, RoHS",customOptions:"Custom color matching, card packaging, multi-pair combo sets",targetBuyers:"Optical chains, kids & fashion eyewear brands, Amazon/e-commerce sellers",description:"Solid 3D star-shaped silicone anti-slip temple stoppers. Engineered with a flexible self-locking internal aperture that accommodates both ultra-thin metal wire and wide acetate temples (1.5–10mm). Prevents slipping while adding a stylish accent. Extremely popular for kids, teens, and active daily wear.",tags:["kids","bestseller","high-margin"]},
  { id:"EH-009",category:"ear",name:"Crescent Moon & Star Silicone Ear Grips",nameCN:"星月造型硅胶眼镜防滑套 (弯月+星星系列)",image:"images/products/EH-009-v2.jpg",specs:{material:"Food-grade ultra-soft silicone (BPA-free)",design:"Ergonomic celestial crescent moon & star shapes",size:"13×12mm (Moon) / 13×13mm (Star), elastic fit for 1.5–9mm temples",color:"Sky Blue, Mint Cyan, Classic Black, Brown, Pastel Pink, Purple, Clear White",packaging:"OPP bag / custom card pack / multi-pair blister"},pricing:[{qty:"100-500",price:"$0.12/pair"},{qty:"500-2000",price:"$0.08/pair"},{qty:"2000+",price:"$0.05/pair"}],moq:100,leadtime:"3-7 days (stock) / 10-15 days (custom)",certifications:"FDA, REACH, LFGB, RoHS",customOptions:"Custom color matching, blister card branding, mix-and-match pairs",targetBuyers:"Children's eyewear brands, optical retail chains, Amazon sellers, school & sports accessories retailers",description:"Playful Star & Crescent Moon silicone anti-slip ear grips for eyeglass temple tips. Ergonomically contoured to grip behind the ears without pressure points or hair pulling. Fits slim metal wire and standard acetate temples (1.5mm–9mm), providing reliable all-day stay-put performance for kids, students, and sports activities.",tags:["kids","bestseller","high-margin"]},

  // --- Category: Temple Tips (7) ---
  { id:"TT-001",category:"temple",name:"Slotted Silicone Temple Tip Sleeves",nameCN:"开槽防滑硅胶眼镜腿套 (56×8mm 舒适防脱)",image:"images/products/TT-001-v2.jpg",specs:{material:"Food-grade soft silicone (FDA, RoHS)",size:"56×8mm, slotted ergonomic curve, fits 3-12mm temple arms",color:"11 Colors (Black, Gray, Dark Gray, Brown, Blue, Red, White, Pink, Orange, Purple, Yellow)",packaging:"OPP bag / custom card pack / pair packaging"},pricing:[{qty:"100-500",price:"$0.12/pair"},{qty:"500-2000",price:"$0.08/pair"},{qty:"2000+",price:"$0.05/pair"}],moq:100,leadtime:"3-7 days (stock) / 10-15 days (custom)",certifications:"FDA, REACH, LFGB, RoHS",customOptions:"11 color choices, custom length/hardness, branded packaging",targetBuyers:"Optical frame manufacturers, optical chains, repair shops, Amazon sellers",description:"Ergonomic 56×8mm slotted silicone eyeglass temple tip sleeves. Features an open-groove flexible design that slips easily over temple curves, providing soft cushioning behind the ears, reducing temple pressure, and preventing frame slippage. Available in 11 colors for metal, TR90, and acetate frames.",tags:["bestseller","high-margin"]},
  { id:"TT-002",category:"temple",name:"Silicone Temple Tip Sleeves with Triangle Ear Hook",nameCN:"带三角耳钩防滑硅胶镜腿套",image:"images/products/TT-002-v2.jpg",specs:{material:"Food-grade high-elastic silicone (FDA, RoHS)",size:"55mm length, ergonomic slotted sleeve with triangle hook",color:"4 Colors (Black, Gray, White, Brown)",packaging:"OPP bag / custom card pack / pair packaging"},pricing:[{qty:"100-500",price:"$0.18/pair"},{qty:"500-2000",price:"$0.12/pair"},{qty:"2000+",price:"$0.08/pair"}],moq:100,leadtime:"5-10 days",certifications:"FDA, REACH",customOptions:"Color matching (Black, Gray, White, Brown), custom card packaging",targetBuyers:"Safety glasses, sports brands, optical chains",description:"Dual-function silicone temple tip sleeves featuring an integrated triangular ear hook. The open slotted channel slides securely onto acetate, TR90, and metal temples, while the flexible triangle hook provides secure anchor behind the ears to completely prevent glasses from slipping.",tags:["bestseller","sports"]},
  { id:"TT-003",category:"temple",name:"Slim Slotted Silicone Temple Tip Sleeves",nameCN:"超细腿开槽防滑硅胶镜腿套 (52mm 金属细腿专用)",image:"images/products/TT-003-v2.jpg",sizeImage:"images/products/TT-003-size.jpg",specs:{material:"Food-grade soft silicone (FDA, RoHS)",totalLength:"52mm",tipDiameter:"4.5mm",slotLength:"40mm (stretchable flexible opening)",aperture:"Φ2.2mm round hole",compatibleTemples:"Fit for thin metal & wire temple arms (1mm–3mm)",color:"4 Colors (Black, White, Gray, Brown)",packaging:"OPP bag / custom card pack / pair packaging"},pricing:[{qty:"MOQ 100+",price:"Contact for Quote"}],moq:"100 (Inquire)",leadtime:"Inquire to Confirm",certifications:"FDA, REACH, RoHS",customOptions:"Color matching (Black, White, Gray, Brown), custom card packaging",targetBuyers:"Optical frame manufacturers, thin-frame eyewear brands, optical retail chains, Amazon sellers",description:"Ultra-slim slotted silicone temple tip sleeves specifically engineered for thin metal wire and delicate acetate temples. Features a 52mm total length with a 40mm flexible stretchable slot and Φ2.2mm aperture, providing snug, anti-slip cushioning behind the ears without adding bulk.",tags:["bestseller","high-margin"]},
  { id:"TT-004",category:"temple",name:"Dual-Slot Silicone Temple Tip Sleeves",nameCN:"双开槽防滑硅胶眼镜腿套 (55mm 弧形缓冲)",image:"images/products/TT-004-v2.jpg",sizeImage:"images/products/TT-004-size.jpg",specs:{material:"Food-grade soft silicone (FDA, RoHS)",totalLength:"55mm",outerHeight:"7mm",innerSlotThickness:"3mm",compatibleTemples:"Fits 3mm–12mm wide temples (acetate & metal)",color:"6 Colors (Black, White, Gray, Brown, Blue, Pink)",packaging:"OPP bag / custom card pack / pair packaging"},pricing:[{qty:"MOQ 100+",price:"Contact for Quote"}],moq:"100 (Inquire)",leadtime:"Inquire to Confirm",certifications:"FDA, REACH, RoHS",customOptions:"Color matching (6 colors), custom card packaging, branded pairs",targetBuyers:"Optical frame manufacturers, eyewear chains, Amazon/e-commerce sellers",description:"Dual-groove ergonomic silicone temple tip sleeves. Features a 55mm total length, 7mm height, and 3mm slot thickness, designed with a two-section flex joint to conform smoothly along curved ear bends on 3–12mm wide temples. Effectively cushions ear pressure and prevents glasses from slipping.",tags:["bestseller","high-margin"]},
  { id:"TT-005",category:"temple",name:"Slim Wire Temple Sleeves with Triangle Ear Hook",nameCN:"超细金属腿带三角耳钩硅胶镜腿套 (59mm)",image:"images/products/TT-005-v2.jpg",sizeImage:"images/products/TT-005-size.jpg",specs:{material:"Soft silicone",totalLength:"59mm",hookHeight:"15mm",tipDiameter:"3mm",compatibleTemples:"Fits 1.0mm–1.3mm metal wire temples",color:"4 Colors (Black, White, Gray, Brown)",packaging:"OPP bag / custom card pack / pair packaging"},pricing:[{qty:"MOQ: Contact for Quote",price:"Contact for Quote"}],moq:"Contact to confirm",leadtime:"Contact to confirm",certifications:"Contact to confirm",customOptions:"Color matching (Black, White, Gray, Brown), custom card packaging",targetBuyers:"Optical frame manufacturers, thin-frame eyewear brands, optical retail chains, Amazon sellers",description:"Ultra-fine wire temple silicone sleeves with integrated triangle ear hook. Designed specifically for slim metal temples (1.0mm–1.3mm width). 59mm overall length with 15mm triangle hook and 3mm tip diameter provides secure slip prevention and behind-the-ear comfort on delicate metal frames.",tags:["bestseller"]},
  { id:"TT-006",category:"temple",name:"Ultra-Slim Tubular Silicone Temple Tip Sleeves",nameCN:"超细管状硅胶防滑镜腿套 (56mm 金属腿专用)",image:"images/products/TT-006-v2.jpg",sizeImage:"images/products/TT-006-size.jpg",specs:{material:"Soft silicone",totalLength:"56mm",outerDiameter:"2.6mm",stretchableLength:"Up to 130mm (stretchable)",aperture:"1mm × 1mm",compatibleTemples:"Fits slim metal wire temples",color:"2 Colors (Black, White)",packaging:"OPP bag / custom card pack / pair packaging"},pricing:[{qty:"MOQ: Contact for Quote",price:"Contact for Quote"}],moq:"Contact to confirm",leadtime:"Contact to confirm",certifications:"Contact to confirm",customOptions:"Color matching (Black, White), custom card packaging",targetBuyers:"Optical frame manufacturers, wire frame brands, optical retail chains, Amazon sellers",description:"Ultra-slim tubular silicone temple tip sleeves designed specifically for slim metal wire eyeglass frames. Features a 56mm length, 2.6mm outer diameter, and 1mm×1mm aperture with high elasticity (stretchable up to 130mm). Provides smooth, seamless slip-prevention and anti-allergy protection on metal temples without adding bulk.",tags:["bestseller"]},
  { id:"TT-007",category:"temple",name:"Through-Hole Silicone Temple Tip Sleeves",nameCN:"方形通孔硅胶眼镜腿套 (60×3mm 金属腿专用)",image:"images/products/TT-007-v2.jpg",sizeImage:"images/products/TT-007-size.jpg",specs:{material:"Silicone",model:"ET011",totalLength:"60mm",outerWidth:"3mm",aperture:"3mm square through-hole",unitWeight:"0.003kg / pair",compatibleTemples:"Fits metal wire temples",color:"4 Colors (Black, White, Brown, Gray)",packaging:"1 pair (2 pcs) / OPP bag / custom packaging"},pricing:[{qty:"MOQ: Contact for Quote",price:"Contact for Quote"}],moq:"Contact to confirm",leadtime:"Contact to confirm",certifications:"Contact to confirm",customOptions:"Color matching (Black, White, Brown, Gray), custom card packaging",targetBuyers:"Optical frame manufacturers, metal eyewear brands, optical retail chains, Amazon sellers",description:"Model ET011 through-hole silicone temple tip sleeves designed for metal wire frames. Features a 60mm length, 3mm width, and 3mm square aperture with ribbed inner friction lines. Lightweight at 3g/pair, providing comfortable, slip-resistant cushioning on metal temples.",tags:["bestseller"]},

  // --- Category: Straps & Cords (3) ---
  { id:"ST-001",category:"strap",name:"Adjustable Silicone Eyeglass Strap",nameCN:"可调节硅胶眼镜绳",image:"images/products/ST-001.jpg",specs:{material:"Silicone cord + plastic adjuster",size:"Φ3mm × 650mm adjustable",color:"Black, Gray, Blue, Red, Custom"},pricing:[{qty:"100-500",price:"$0.35/pc"},{qty:"500-2000",price:"$0.22/pc"},{qty:"2000+",price:"$0.15/pc"}],moq:100,leadtime:"5-10 days",certifications:"FDA, REACH",customOptions:"Color, length, logo printing, packaging",targetBuyers:"Outdoor brands, promo buyers, sports retail",description:"Lightweight adjustable eyeglass strap for outdoor and sports use. High repurchase rate.",tags:["bestseller","high-margin"]},
  { id:"ST-002",category:"strap",name:"Silicone + Metal Beaded Eyeglass Chain",nameCN:"硅胶金属珠眼镜链",image:"images/products/ST-002.jpg",specs:{material:"Silicone cord + zinc alloy beads",size:"700mm total length",color:"Gold, Silver, Rose Gold"},pricing:[{qty:"50-200",price:"$1.80/pc"},{qty:"200-1000",price:"$1.20/pc"},{qty:"1000+",price:"$0.85/pc"}],moq:50,leadtime:"10-15 days",certifications:"RoHS, REACH",customOptions:"Bead design, metal finish, cord color",targetBuyers:"Fashion accessory brands, boutique optical",description:"Fashion-forward eyeglass chain with silicone comfort and metallic elegance.",tags:["fashion","premium"]},
  { id:"ST-003",category:"strap",name:"Neoprene + Silicone Sports Eyeglass Strap",nameCN:"潜水料+硅胶运动眼镜绑带",image:"images/products/ST-003.jpg",specs:{material:"Neoprene strap + silicone grips",size:"Adjustable 300-500mm",color:"Black, Navy, Camo, Custom"},pricing:[{qty:"100-500",price:"$0.65/pc"},{qty:"500-2000",price:"$0.45/pc"},{qty:"2000+",price:"$0.30/pc"}],moq:100,leadtime:"10-15 days",certifications:"REACH",customOptions:"Width, print, grip color, logo",targetBuyers:"Water sports, outdoor gear companies",description:"Heavy-duty neoprene strap for surfing, kayaking, extreme sports. Floats in water.",tags:["sports","premium"]},

  // --- Category: Smart Glasses (4) ---
  { id:"SG-001",category:"smart",name:"Meta Ray-Ban Wayfarer Silicone Nose Pads (10pk)",nameCN:"Meta Ray-Ban Wayfarer 硅胶鼻托10对装",image:"images/products/SG-001.jpg",specs:{material:"Soft silicone (35 Shore A)",compat:"Meta Ray-Ban Wayfarer Gen 1/2",size:"Custom-fit, self-adhesive",color:"Black, Clear"},pricing:[{qty:"50-200",price:"$0.35/pair"},{qty:"200-1000",price:"$0.22/pair"},{qty:"1000-5000",price:"$0.15/pair"},{qty:"5000+",price:"$0.10/pair"}],moq:50,leadtime:"5-10 days",certifications:"FDA",customOptions:"Packaging, branding",targetBuyers:"Smart glasses accessory brands, Amazon sellers",description:"Precision-cut nose pads for Meta Ray-Ban Wayfarer. 300% YoY growth. #1 smart glasses accessory.",tags:["bestseller","high-margin","trending"]},
  { id:"SG-002",category:"smart",name:"Meta Ray-Ban Headliner Silicone Nose Pads (10pk)",nameCN:"Meta Ray-Ban Headliner 硅胶鼻托10对装",image:"images/products/SG-002.jpg",specs:{material:"Soft silicone (35 Shore A)",compat:"Meta Ray-Ban Headliner Gen 1/2",size:"Custom-fit, self-adhesive",color:"Black, Clear"},pricing:[{qty:"50-200",price:"$0.35/pair"},{qty:"200-1000",price:"$0.22/pair"},{qty:"1000+",price:"$0.15/pair"}],moq:50,leadtime:"5-10 days",certifications:"FDA",customOptions:"Packaging, branding",targetBuyers:"Smart glasses accessory brands",description:"Precision-cut nose pads for Meta Ray-Ban Headliner. Same premium quality.",tags:["high-margin","trending"]},
  { id:"SG-003",category:"smart",name:"Meta Ray-Ban Anti-Slip Silicone Ear Hooks",nameCN:"Meta Ray-Ban 防滑硅胶耳钩",image:"images/products/SG-003.jpg",specs:{material:"Ergonomic silicone (40 Shore A)",compat:"Meta Ray-Ban Wayfarer & Headliner Gen 1/2",size:"Curved hook, slip-on",color:"Black, Clear"},pricing:[{qty:"50-200",price:"$0.55/pair"},{qty:"200-1000",price:"$0.38/pair"},{qty:"1000+",price:"$0.25/pair"}],moq:50,leadtime:"7-12 days",certifications:"FDA",customOptions:"Color, packaging",targetBuyers:"Smart glasses, 3C accessory sellers",description:"Ergonomic ear hooks for Meta Ray-Ban. Secure fit without interfering with touch controls.",tags:["high-margin","trending"]},
  { id:"SG-004",category:"smart",name:"Universal AR Glasses Silicone Nose Pad Kit",nameCN:"通用AR眼镜硅胶鼻托套装3种高度",image:"images/products/SG-004.jpg",specs:{material:"Soft silicone",compat:"XREAL Air, Rokid, Nreal, Viture, and more",size:"3 heights (S/M/L) included",color:"Black"},pricing:[{qty:"50-300",price:"$0.60/set"},{qty:"300-1000",price:"$0.42/set"},{qty:"1000+",price:"$0.30/set"}],moq:50,leadtime:"7-12 days",certifications:"FDA",customOptions:"Brand-specific kits, retail packaging",targetBuyers:"AR glasses accessory brands, tech sellers",description:"Universal 3-height nose pad kit for major AR glasses brands. Perfect fit and viewing angle.",tags:["trending"]},

  // --- Category: Kits & Sets (4) ---
  { id:"KT-001",category:"kit",name:"Eyeglass Care Kit (Pads+Hooks+Cloth+Tool)",nameCN:"眼镜护理套装完整版",image:"images/products/KT-001.jpg",specs:{contents:"5pr nose pads + 5pr ear hooks + microfiber cloth + mini screwdriver",packaging:"Custom box or tin case",material:"All silicone parts food-grade"},pricing:[{qty:"200-500",price:"$1.20/set"},{qty:"500-2000",price:"$0.85/set"},{qty:"2000+",price:"$0.60/set"}],moq:200,leadtime:"10-15 days",certifications:"FDA, LFGB",customOptions:"Box design, logo, colors, contents mix",targetBuyers:"Optical chains, eyewear brands for retail/GWP",description:"Complete eyeglass care kit in branded packaging. Avg order 5,000-20,000 units.",tags:["premium","high-margin"]},
  { id:"KT-002",category:"kit",name:"Children's Eyewear Anti-Slip Bundle",nameCN:"儿童眼镜防滑套装",image:"images/products/KT-002.jpg",specs:{contents:"U-shape nose pad + 2pr ear hooks + adjustable strap",packaging:"Colorful hang-sell card",material:"BPA-free silicone, food-grade"},pricing:[{qty:"100-500",price:"$0.55/set"},{qty:"500-2000",price:"$0.38/set"},{qty:"2000+",price:"$0.28/set"}],moq:100,leadtime:"7-12 days",certifications:"FDA, LFGB, BPA-free",customOptions:"Character designs, colors, packaging",targetBuyers:"Children's eyewear brands, parent retail",description:"All-in-one anti-slip solution for kids glasses. Fun, safe. 42%+ repurchase rate.",tags:["kids","high-margin"]},
  { id:"KT-003",category:"kit",name:"Professional Optical Repair Kit",nameCN:"专业眼镜维修配件包",image:"images/products/KT-003.jpg",specs:{contents:"20pr assorted nose pads + 10pr ear hooks + screwdriver + screws",packaging:"Plastic organizer box",material:"Silicone + metal"},pricing:[{qty:"100-500",price:"$1.80/set"},{qty:"500-2000",price:"$1.25/set"},{qty:"2000+",price:"$0.90/set"}],moq:100,leadtime:"10-15 days",certifications:"FDA, RoHS",customOptions:"Box branding, assortment mix",targetBuyers:"Optical repair shops, optometrists",description:"Comprehensive repair kit for optical professionals. Most common replacement parts.",tags:["professional"]},
  { id:"KT-004",category:"kit",name:"Smart Glasses Accessory Starter Pack",nameCN:"智能眼镜配件入门包",image:"images/products/KT-004.jpg",specs:{contents:"10pr smart glasses nose pads mixed + 5pr ear hooks",packaging:"Retail-ready blister card",material:"Premium silicone"},pricing:[{qty:"100-500",price:"$1.00/set"},{qty:"500-2000",price:"$0.70/set"},{qty:"2000+",price:"$0.50/set"}],moq:100,leadtime:"7-12 days",certifications:"FDA",customOptions:"Brand-specific packaging, model mix",targetBuyers:"Smart glasses brands, tech accessory sellers",description:"Curated mix pack for smart glasses users. Includes most popular sizes for Meta, XREAL, Huawei.",tags:["trending","high-margin"]}
];

var categories = [
  { id:"all",icon:"⊞" },{ id:"nose",icon:"◉" },{ id:"ear",icon:"↻" },
  { id:"temple",icon:"▬" },{ id:"strap",icon:"～" },
  { id:"smart",icon:"◆" },{ id:"kit",icon:"⊡" }
];

var caseStudies = [
  { id:"CS-001",titleKey:"case1_title",descKey:"case1_desc",industry:"Optical Retail Chain",location:"United States",orderSize:"50,000 pairs/month",results:"35% cost reduction, 98% quality acceptance"},
  { id:"CS-002",titleKey:"case2_title",descKey:"case2_desc",industry:"DTC Eyewear Brand",location:"Germany",orderSize:"30,000 units initial, 15,000/month",results:"60% margin, 4.8★ customer rating"},
  { id:"CS-003",titleKey:"case3_title",descKey:"case3_desc",industry:"Smart Glasses Accessories",location:"United States / Global",orderSize:"20,000+ units/month, 5 SKUs",results:"10-day time-to-market, #1 Amazon BSR"}
];

var suppliers = [
  { name:"Xiamen Xinhuabao Silicone",years:21,location:"Xiamen, Fujian",moq:"500/1000 (custom)",sampleDays:"5-7 days",deliveryDays:"10-15 days",certs:"ISO 9001",rating:5 },
  { name:"Quanzhou Shengda Rubber",years:12,location:"Quanzhou, Fujian",moq:"100/500 (custom)",sampleDays:"3-5 days",deliveryDays:"7-12 days",certs:"ISO 9001",rating:4 },
  { name:"Dongguan Yongcheng New Material",years:10,location:"Dongguan, Guangdong",moq:"200/1000 (custom)",sampleDays:"7-10 days",deliveryDays:"10-15 days",certs:"FDA, LFGB, REACH",rating:5 }
];
